# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20161226_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_header',
            field=models.CharField(default='No subject', max_length=100),
        ),
    ]
